[package]
name = "parsec-kak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec-core = { version = "*", path = "../parsec-core" }
crossterm = "*"
