[package]
name = "parsec-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec-term = { path = "../parsec/parsec-term", version = "*" }
parsec-core = { path = "../parsec/parsec-core", version = "*" }
parsec-kak = { path = "../parsec/parsec-kak", version = "*" }

crossterm = { path = "../crossterm/" }
