max_width = 100
use_small_heuristics = "Max"
array_width = 99
attr_fn_like_width = 99
chain_width = 99
combine_control_expr = true
comment_width = 99
empty_item_single_line = true
fn_args_layout = "Compressed"
fn_call_width = 99
force_explicit_abi = true
format_code_in_doc_comments = true
format_macro_bodies = true
group_imports = "StdExternalCrate"
hex_literal_case = "Preserve"
imports_granularity = "Preserve"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
merge_derives = true
newline_style = "Auto"
overflow_delimited_expr = true
reorder_impl_items = true
short_array_element_width_threshold = 10
single_line_if_else_max_width = 99
struct_lit_single_line = true
struct_lit_width = 99
struct_variant_width = 99
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = false
use_try_shorthand = false
version = "Two"
where_single_line = false
wrap_comments = true
