[package]
name = "duat-term"
version = "0.2.0"
authors = ["AhoyISki"]
description = "A frontend for Duat for the terminal"
repository = "https://github.com/AhoyISki/parsec/tree/master/parsec-term"
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["editor", "terminal", "text", "duat"]
categories = ["command-line-utilities", "text-editors", "config"]
edition = "2021"

[dependencies]
duat-core = { path = "../duat-core/", version = ">=0.2.0" }

unicode-width = ">=0.1.10"
crossterm = ">=0.28.0"
smallvec = ">=1.10.0"
cassowary = ">=0.3.0"
