name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - AhoyISki
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this bug report!
  - type: checkboxes
    id: is-duat-related
    attributes:
      label: Is this issue duat related? Or is it related to some plugin or extension?
      description: |
        For example, if your issue is about syntax highlighting, it is probably related
        to [`duat-treesitter`](https://github.com/AhoyISki/duat-treesitter), not duat.      
      options:
        - label: Yes, it is most closely related to duat.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: How did duat mess up this time? How did you expect duat _not_ to mess up?
      placeholder: Duat bad
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version of duat are you using?
      description: For now, the recommended version is the latest one from github.
      options:
        - Latest from github
        - Latest from crates.io
        - Something else 🤨
      default: 0
    validations:
      required: true
  - type: textarea
    id: latest-rust-version
    attributes:
      label: |
        What version of rust are you using? Paste the output of `rustc --version` below.
      description: |
        Remember, Duat only has a commitment to support the latest version of rust stable
        (and probably nightly too). If you have problems compiling, the toolchain version
        is a likely culprit.
        You can relieve that by running `rustup update`. This is extremely unlikely to
        result in your config no longer compiling if it wasn't compiling before.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What operating system(s) are you using?
      description: |
        Linux, MacOS and Windows should be supported. There are a few kinks with Windows at the moment,
        but feel free to report bugs for any of these operating systems.
      placeholder: linux
      value: linux
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Additional context
      description: |
        What other bits of information do you think are worth mentioning?
      placeholder: Not much, hbu
