name: "Feature Request"
description: "Request a feature."
title: "[Feat]: "
labels: ["enhancement"]
assignees:
  - AhoyISki
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this feature request!
  - type: checkboxes
    id: was-requested-before
    attributes:
      label: Have you checked if this feature was already requested?
      description: |
        Try searching the issues of Duat, see if you can find something that resembles
        what you're asking for.
      options:
        - label: This was not requested before.
          required: true
  - type: textarea
    id: request
    attributes:
      label: What would you like?
      placeholder: Duat not good enough
    validations:
      required: true
  - type: dropdown
    id: is-valid
    attributes:
      label: In your opinion, is this request valid?
      description: |
        Does this belong on the core crates of duat? Could it be implemented as a plugin?
        Is it needlesly difficult to implement this as a plugin?
      options:
        - It belongs in duat, I think.
        - It might be implementable as a plugin.
        - I thought about it, and implementing it as a plugin seems too hard/not possible.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: "What version of duat are you using?"
      description: "The recommended version is the latest one on crates.io or github."
      options:
        - "Latest from github"
        - "Latest from crates.io"
        - "Something else 🤨"
      default: 0
    validations:
      required: true
