[package]
name = "parsec-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Style handling
crossterm = "0.26.0"

# Utility
bitflags = "1.3.2"
regex = "1.7.1"
smallvec = "1.10.0"
