[package]
name = "parsec-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Unicode
unicode-segmentation = "*"
unicode-width = "*"

# Style handling
crossterm = { git = "https://github.com/crossterm-rs/crossterm", branch = "master" }

# Utility
bitflags = "*"
regex = "*"
smallvec = "*"
copypasta = "*"
wl-clipboard-rs = "*"
