title: The Duat text editor
email: ahoyiski@gmail.com
description: A text editor focused on great extensibility, but with great defaults.
baseurl: "duat"
url: "https://ahoyiski.github.io"
twitter_username: AhoyISki
github_username:  AhoyISki
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
