title: The Duat text editor
email: ahoyiski@gmail.com
description: A text editor easy to extend greatly, while having great defaults.
baseurl: "duat"
url: "https://ahoyiski.github.io"
twitter_username: AhoyISki
github_username:  AhoyISki
theme: jekyll-theme-minimal
