[package]
name = "parsec-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-width = "0.1.10"

crossterm = "0.26.0"
parsec-core = "0.1.0"
