name: "Generate tree-sitter language objects"

on: [release, workflow_dispatch]

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          
  generate-languages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang:
          - name: "rust"
            url: "tree-sitter/tree-sitter-rust"
          - name: "python"
            url: "tree-sitter/tree-sitter-python"
          - name: "javascript"
            url: "tree-sitter/tree-sitter-javascript"

    steps:
      - name: "Checkout Language Repository"
        uses: actions/checkout@v7
        with:
          repository: ${{ matrix.lang.url }}
          path: ${{ matrix.lang.name }}



      - name: "Setup Tree-sitter CLI"
        uses: tree-sitter/setup-action@v2

      - name: "Generate and Compile Language Object"
        working-directory: ${{ matrix.lang.name }}
        run: "tree-sitter build && pwd"

      - uses: actions/upload-artifact@v7
        with:
          name: "${{ matrix.lang.name }}_parser.so"
          path: "${{ matrix.lang.name }}/parser.so"

  merge-artifacts:
    runs-on: ubuntu-latest
    needs: generate-languages
    steps:
      - name: Merge all matrix reports
        uses: actions/upload-artifact/merge@v4
        with:
          name: parsers
          pattern: *_parser.so
          delete-merged: true
          
        
